In [2]:
import torch

In [3]:
a = torch.tensor([2.], requires_grad=True)

In [4]:
b = a ** 2
b

tensor([4.], grad_fn=<PowBackward0>)

In [5]:
b.backward()

In [6]:
a.grad

tensor([4.])

In [7]:
x = torch.ones(2, 3, requires_grad=True)
y = torch.randn(2, 3, 4, requires_grad=True)

In [8]:
l = torch.exp(y.sum(dim=-1) + x.tanh()).sum()
l

tensor(512.5875, grad_fn=<SumBackward0>)

In [9]:
l.backward()

In [10]:
x.grad, y.grad

(tensor([[  1.9670, 163.6919,   0.4250],
         [ 12.2165,  34.1928,   2.7804]]),
 tensor([[[  4.6836,   4.6836,   4.6836,   4.6836],
          [389.7664, 389.7664, 389.7664, 389.7664],
          [  1.0119,   1.0119,   1.0119,   1.0119]],
 
         [[ 29.0886,  29.0886,  29.0886,  29.0886],
          [ 81.4164,  81.4164,  81.4164,  81.4164],
          [  6.6205,   6.6205,   6.6205,   6.6205]]]))

In [11]:
# nvidia-smi

# надо задать CUDA_VISIBLE_DEVICES

In [12]:
torch.cuda.is_available()

False

In [13]:
torch.cuda.device_count()

0

In [14]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

device 

device(type='cpu')

In [15]:
x = torch.randn(10, 10).to(device)
x

tensor([[ 0.5819,  0.5553,  0.3415, -2.0552, -0.8063,  0.1529,  0.6913, -1.1577,
          1.1548, -0.1031],
        [ 0.1440,  1.1833,  0.1828,  0.0487, -1.1334,  1.2924,  0.4541,  0.9322,
          0.0245, -0.7046],
        [ 0.9559,  0.5910, -0.6851, -0.1856,  0.1928, -1.0269,  1.3395, -1.0617,
          0.9762,  0.7703],
        [-0.0843,  2.2140,  0.4254, -0.7931,  0.4965,  0.8879, -0.7266,  0.7435,
         -0.0995,  0.0933],
        [-1.8972,  0.8443, -1.5881, -1.2946,  0.3847,  0.1061,  2.4506, -0.4966,
         -0.3914,  0.9216],
        [-0.8038, -0.2570,  1.0000,  0.2745,  0.8003, -0.2056, -1.3348,  0.5902,
         -0.7856,  0.6907],
        [-0.0383,  1.8459,  0.1819, -1.4486,  0.2156,  0.6541, -1.2256, -2.6830,
         -1.3826,  0.3183],
        [ 0.0077,  1.2174, -0.9221, -1.5053,  1.1324, -0.4298,  1.2804,  1.0600,
          0.4906,  2.8617],
        [-0.0451, -0.0666, -0.0984, -0.8586,  0.6104,  1.6173,  0.7212,  0.3299,
          0.3736, -0.0799],
        [ 0.5370, -

In [16]:
# лучше так
x = torch.randn(10, 10, device=device)
x

tensor([[ 5.5189e-02, -5.5069e-01, -8.7966e-01,  7.1875e-01, -8.5452e-01,
         -6.1617e-01, -1.2100e+00, -3.2117e-01,  1.5108e+00,  4.7990e-01],
        [-2.0026e-01, -6.8686e-02,  2.0019e-01, -1.4082e+00,  5.6609e-01,
          8.0135e-01, -1.7655e+00,  1.8513e-01,  1.2268e+00, -1.4691e-01],
        [-6.1973e-01, -2.0612e-01, -2.0163e-01, -1.6822e+00, -5.6973e-01,
          2.3016e-01,  1.8199e+00, -6.0601e-01,  1.8222e+00, -1.0267e+00],
        [ 4.4810e-01, -4.5064e-01, -8.3961e-01,  1.4339e+00,  1.0655e+00,
          1.0620e-01, -1.3692e-03,  7.9362e-01, -1.7878e+00, -3.7470e-01],
        [-1.1896e+00,  2.5299e-01, -4.2385e-02, -1.9744e+00, -4.9010e-02,
          3.8916e-01,  2.7970e-01,  2.2246e-01,  3.6723e-01, -1.1480e+00],
        [ 2.2390e+00, -1.4672e+00,  3.4744e-01,  8.5635e-01, -1.0101e+00,
          4.3126e-01,  2.5409e-02,  6.1551e-01,  9.4775e-01, -7.1268e-01],
        [ 8.6385e-01,  1.3155e+00, -1.5511e-02,  5.5704e-01,  2.7856e+00,
          1.2184e+00,  3.7900e-0

In [17]:
# вернуться обратно
# x = x.cpu()

In [18]:
# про логеры

In [26]:
N = 5000
a = torch.randn(N, N)

In [27]:
a_python = a.tolist()

In [28]:
%%time 
sum(a_python[i][j] for i in range(N) for j in range(N))

CPU times: user 2.86 s, sys: 39 ms, total: 2.89 s
Wall time: 2.98 s


-558.11372067233

In [29]:
a_numpy = a.numpy()

In [30]:
%%time
a_numpy.sum()

CPU times: user 13.2 ms, sys: 2.34 ms, total: 15.6 ms
Wall time: 14.2 ms


-558.11554

In [32]:
%%time
a.sum()

CPU times: user 12.9 ms, sys: 2.45 ms, total: 15.4 ms
Wall time: 18.3 ms


tensor(-558.1119)

In [33]:
x = torch.randn(5, 5, requires_grad=True)
y = torch.randn(5, 5, requires_grad=False)

In [34]:
l = (x * y).sum()

In [35]:
l.backward()

In [36]:
x.grad, y.grad

(tensor([[-0.0118, -0.5811,  0.0296,  0.8157,  0.2728],
         [ 1.8181,  0.9786, -0.0305, -0.0955,  0.4420],
         [-0.3673, -1.6517,  1.2184,  1.2487, -0.7742],
         [ 1.3379,  1.3560, -1.3701,  0.8139,  1.5393],
         [-0.5162, -0.9192,  1.0636, -1.0980,  2.3823]]),
 None)

In [37]:
with torch.no_grad():
    l = (x * y).sum()
    l.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [39]:
# лучше оптимизация, чем no_grad

with torch.inference_mode():
    l = (x * y).sum()
    l.backward()    

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [43]:
torch.__version__

'1.12.1'